package com.eCommerce.shopify.model.orderDetails
import android.os.Parcelable
import com.eCommerce.shopify.model.Addresse
import com.eCommerce.shopify.model.Customer
import kotlinx.parcelize.Parcelize

@Parcelize
data class Order(
    val admin_graphql_api_id: String? = null,
    val billing_address: Addresse? = null,
    val browser_ip: String? = null,
    val buyer_accepts_marketing: Boolean? = null,
    val cart_token: String? = null,
    val checkout_id: Int? = null,
    val checkout_token: String? = null,
    val client_details: ClientDetails? = null,
    val confirmed: Boolean? = null,
    val contact_email: String? = null,
    val created_at: String? = null,
    val currency: String? = null,
    val current_subtotal_price: String? = null,
    val current_subtotal_price_set: CurrentSubtotalPriceSet? = null,
    val current_total_discounts: String? = null,
    val current_total_discounts_set: CurrentTotalDiscountsSet? = null,
    val current_total_price: String? = null,
    val current_total_price_set: CurrentTotalPriceSet? = null,
    val current_total_tax: String? = null,
    val current_total_tax_set: CurrentTotalTaxSet? = null,
    var customer: Customer? = null,
    val customer_locale: String? = null,
    val discount_applications: List<DiscountApplication>? = null,
    val discount_codes: List<DiscountCode>? = null,
    val email: String? = null,
    val estimated_taxes: Boolean? = null,
    val financial_status: String? = null,
    val gateway: String? = null,
    val id: Long? = null,
    val landing_site: String? = null,
    val landing_site_ref: String? = null,
    val line_items: List<LineItem>? = null,
    val name: String? = null,
    val note_attributes: List<NoteAttribute>? = null,
    val number: Int? = null,
    val order_number: Int? = null,
    val order_status_url: String? = null,
    val payment_details: PaymentDetails? = null,
    val payment_gateway_names: List<String>? = null,
    val phone: String? = null,
    val presentment_currency: String? = null,
    val processed_at: String? = null,
    val processing_method: String? = null,
    val reference: String? = null,
    val referring_site: String? = null,
    val shipping_address: Addresse? = null,
    val shipping_lines: List<ShippingLine>? = null,
    val source_identifier: String? = null,
    val source_name: String? = null,
    val subtotal_price: String? = null,
    val subtotal_price_set: SubtotalPriceSet? = null,
    val tags: String? = null,
    val tax_lines: List<TaxLine>? = null,
    val taxes_included: Boolean? = null,
    val test: Boolean? = null,
    val token: String? = null,
    val total_discounts: String? = null,
    val total_discounts_set: TotalDiscountsSet? = null,
    val total_line_items_price: String? = null,
    val total_line_items_price_set: TotalLineItemsPriceSet? = null,
    val total_outstanding: String? = null,
    val total_price: String? = null,
    val total_price_set: TotalPriceSet? = null,
    val total_price_usd: String? = null,
    val total_shipping_price_set: TotalShippingPriceSet? = null,
    val total_tax: String? = null,
    val total_tax_set: TotalTaxSet? = null,
    val total_tip_received: String? = null,
    val total_weight: Int? = null,
    val updated_at: String? = null,
    val user_id: Long? = null
): Parcelable
